// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ronin-chain/ronin-random-beacon/pkg/db/chaininfo"
)

// ChainInfoCreate is the builder for creating a ChainInfo entity.
type ChainInfoCreate struct {
	config
	mutation *ChainInfoMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProcessedBlock sets the "processed_block" field.
func (cic *ChainInfoCreate) SetProcessedBlock(u uint64) *ChainInfoCreate {
	cic.mutation.SetProcessedBlock(u)
	return cic
}

// SetNillableProcessedBlock sets the "processed_block" field if the given value is not nil.
func (cic *ChainInfoCreate) SetNillableProcessedBlock(u *uint64) *ChainInfoCreate {
	if u != nil {
		cic.SetProcessedBlock(*u)
	}
	return cic
}

// SetID sets the "id" field.
func (cic *ChainInfoCreate) SetID(s string) *ChainInfoCreate {
	cic.mutation.SetID(s)
	return cic
}

// Mutation returns the ChainInfoMutation object of the builder.
func (cic *ChainInfoCreate) Mutation() *ChainInfoMutation {
	return cic.mutation
}

// Save creates the ChainInfo in the database.
func (cic *ChainInfoCreate) Save(ctx context.Context) (*ChainInfo, error) {
	cic.defaults()
	return withHooks(ctx, cic.sqlSave, cic.mutation, cic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cic *ChainInfoCreate) SaveX(ctx context.Context) *ChainInfo {
	v, err := cic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cic *ChainInfoCreate) Exec(ctx context.Context) error {
	_, err := cic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cic *ChainInfoCreate) ExecX(ctx context.Context) {
	if err := cic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cic *ChainInfoCreate) defaults() {
	if _, ok := cic.mutation.ProcessedBlock(); !ok {
		v := chaininfo.DefaultProcessedBlock
		cic.mutation.SetProcessedBlock(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cic *ChainInfoCreate) check() error {
	if _, ok := cic.mutation.ProcessedBlock(); !ok {
		return &ValidationError{Name: "processed_block", err: errors.New(`db: missing required field "ChainInfo.processed_block"`)}
	}
	if v, ok := cic.mutation.ID(); ok {
		if err := chaininfo.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`db: validator failed for field "ChainInfo.id": %w`, err)}
		}
	}
	return nil
}

func (cic *ChainInfoCreate) sqlSave(ctx context.Context) (*ChainInfo, error) {
	if err := cic.check(); err != nil {
		return nil, err
	}
	_node, _spec := cic.createSpec()
	if err := sqlgraph.CreateNode(ctx, cic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ChainInfo.ID type: %T", _spec.ID.Value)
		}
	}
	cic.mutation.id = &_node.ID
	cic.mutation.done = true
	return _node, nil
}

func (cic *ChainInfoCreate) createSpec() (*ChainInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &ChainInfo{config: cic.config}
		_spec = sqlgraph.NewCreateSpec(chaininfo.Table, sqlgraph.NewFieldSpec(chaininfo.FieldID, field.TypeString))
	)
	_spec.OnConflict = cic.conflict
	if id, ok := cic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cic.mutation.ProcessedBlock(); ok {
		_spec.SetField(chaininfo.FieldProcessedBlock, field.TypeUint64, value)
		_node.ProcessedBlock = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChainInfo.Create().
//		SetProcessedBlock(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChainInfoUpsert) {
//			SetProcessedBlock(v+v).
//		}).
//		Exec(ctx)
func (cic *ChainInfoCreate) OnConflict(opts ...sql.ConflictOption) *ChainInfoUpsertOne {
	cic.conflict = opts
	return &ChainInfoUpsertOne{
		create: cic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChainInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (cic *ChainInfoCreate) OnConflictColumns(columns ...string) *ChainInfoUpsertOne {
	cic.conflict = append(cic.conflict, sql.ConflictColumns(columns...))
	return &ChainInfoUpsertOne{
		create: cic,
	}
}

type (
	// ChainInfoUpsertOne is the builder for "upsert"-ing
	//  one ChainInfo node.
	ChainInfoUpsertOne struct {
		create *ChainInfoCreate
	}

	// ChainInfoUpsert is the "OnConflict" setter.
	ChainInfoUpsert struct {
		*sql.UpdateSet
	}
)

// SetProcessedBlock sets the "processed_block" field.
func (u *ChainInfoUpsert) SetProcessedBlock(v uint64) *ChainInfoUpsert {
	u.Set(chaininfo.FieldProcessedBlock, v)
	return u
}

// UpdateProcessedBlock sets the "processed_block" field to the value that was provided on create.
func (u *ChainInfoUpsert) UpdateProcessedBlock() *ChainInfoUpsert {
	u.SetExcluded(chaininfo.FieldProcessedBlock)
	return u
}

// AddProcessedBlock adds v to the "processed_block" field.
func (u *ChainInfoUpsert) AddProcessedBlock(v uint64) *ChainInfoUpsert {
	u.Add(chaininfo.FieldProcessedBlock, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ChainInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chaininfo.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChainInfoUpsertOne) UpdateNewValues() *ChainInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(chaininfo.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChainInfo.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChainInfoUpsertOne) Ignore() *ChainInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChainInfoUpsertOne) DoNothing() *ChainInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChainInfoCreate.OnConflict
// documentation for more info.
func (u *ChainInfoUpsertOne) Update(set func(*ChainInfoUpsert)) *ChainInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChainInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetProcessedBlock sets the "processed_block" field.
func (u *ChainInfoUpsertOne) SetProcessedBlock(v uint64) *ChainInfoUpsertOne {
	return u.Update(func(s *ChainInfoUpsert) {
		s.SetProcessedBlock(v)
	})
}

// AddProcessedBlock adds v to the "processed_block" field.
func (u *ChainInfoUpsertOne) AddProcessedBlock(v uint64) *ChainInfoUpsertOne {
	return u.Update(func(s *ChainInfoUpsert) {
		s.AddProcessedBlock(v)
	})
}

// UpdateProcessedBlock sets the "processed_block" field to the value that was provided on create.
func (u *ChainInfoUpsertOne) UpdateProcessedBlock() *ChainInfoUpsertOne {
	return u.Update(func(s *ChainInfoUpsert) {
		s.UpdateProcessedBlock()
	})
}

// Exec executes the query.
func (u *ChainInfoUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ChainInfoCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChainInfoUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChainInfoUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: ChainInfoUpsertOne.ID is not supported by MySQL driver. Use ChainInfoUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChainInfoUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChainInfoCreateBulk is the builder for creating many ChainInfo entities in bulk.
type ChainInfoCreateBulk struct {
	config
	err      error
	builders []*ChainInfoCreate
	conflict []sql.ConflictOption
}

// Save creates the ChainInfo entities in the database.
func (cicb *ChainInfoCreateBulk) Save(ctx context.Context) ([]*ChainInfo, error) {
	if cicb.err != nil {
		return nil, cicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cicb.builders))
	nodes := make([]*ChainInfo, len(cicb.builders))
	mutators := make([]Mutator, len(cicb.builders))
	for i := range cicb.builders {
		func(i int, root context.Context) {
			builder := cicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChainInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cicb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cicb *ChainInfoCreateBulk) SaveX(ctx context.Context) []*ChainInfo {
	v, err := cicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cicb *ChainInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := cicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cicb *ChainInfoCreateBulk) ExecX(ctx context.Context) {
	if err := cicb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChainInfo.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChainInfoUpsert) {
//			SetProcessedBlock(v+v).
//		}).
//		Exec(ctx)
func (cicb *ChainInfoCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChainInfoUpsertBulk {
	cicb.conflict = opts
	return &ChainInfoUpsertBulk{
		create: cicb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChainInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (cicb *ChainInfoCreateBulk) OnConflictColumns(columns ...string) *ChainInfoUpsertBulk {
	cicb.conflict = append(cicb.conflict, sql.ConflictColumns(columns...))
	return &ChainInfoUpsertBulk{
		create: cicb,
	}
}

// ChainInfoUpsertBulk is the builder for "upsert"-ing
// a bulk of ChainInfo nodes.
type ChainInfoUpsertBulk struct {
	create *ChainInfoCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChainInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chaininfo.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChainInfoUpsertBulk) UpdateNewValues() *ChainInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(chaininfo.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChainInfo.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChainInfoUpsertBulk) Ignore() *ChainInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChainInfoUpsertBulk) DoNothing() *ChainInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChainInfoCreateBulk.OnConflict
// documentation for more info.
func (u *ChainInfoUpsertBulk) Update(set func(*ChainInfoUpsert)) *ChainInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChainInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetProcessedBlock sets the "processed_block" field.
func (u *ChainInfoUpsertBulk) SetProcessedBlock(v uint64) *ChainInfoUpsertBulk {
	return u.Update(func(s *ChainInfoUpsert) {
		s.SetProcessedBlock(v)
	})
}

// AddProcessedBlock adds v to the "processed_block" field.
func (u *ChainInfoUpsertBulk) AddProcessedBlock(v uint64) *ChainInfoUpsertBulk {
	return u.Update(func(s *ChainInfoUpsert) {
		s.AddProcessedBlock(v)
	})
}

// UpdateProcessedBlock sets the "processed_block" field to the value that was provided on create.
func (u *ChainInfoUpsertBulk) UpdateProcessedBlock() *ChainInfoUpsertBulk {
	return u.Update(func(s *ChainInfoUpsert) {
		s.UpdateProcessedBlock()
	})
}

// Exec executes the query.
func (u *ChainInfoUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the ChainInfoCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ChainInfoCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChainInfoUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
