// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ronin-chain/ronin-random-beacon/pkg/db/chaininfo"
	"github.com/ronin-chain/ronin-random-beacon/pkg/db/predicate"
)

// ChainInfoQuery is the builder for querying ChainInfo entities.
type ChainInfoQuery struct {
	config
	ctx        *QueryContext
	order      []chaininfo.OrderOption
	inters     []Interceptor
	predicates []predicate.ChainInfo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChainInfoQuery builder.
func (ciq *ChainInfoQuery) Where(ps ...predicate.ChainInfo) *ChainInfoQuery {
	ciq.predicates = append(ciq.predicates, ps...)
	return ciq
}

// Limit the number of records to be returned by this query.
func (ciq *ChainInfoQuery) Limit(limit int) *ChainInfoQuery {
	ciq.ctx.Limit = &limit
	return ciq
}

// Offset to start from.
func (ciq *ChainInfoQuery) Offset(offset int) *ChainInfoQuery {
	ciq.ctx.Offset = &offset
	return ciq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ciq *ChainInfoQuery) Unique(unique bool) *ChainInfoQuery {
	ciq.ctx.Unique = &unique
	return ciq
}

// Order specifies how the records should be ordered.
func (ciq *ChainInfoQuery) Order(o ...chaininfo.OrderOption) *ChainInfoQuery {
	ciq.order = append(ciq.order, o...)
	return ciq
}

// First returns the first ChainInfo entity from the query.
// Returns a *NotFoundError when no ChainInfo was found.
func (ciq *ChainInfoQuery) First(ctx context.Context) (*ChainInfo, error) {
	nodes, err := ciq.Limit(1).All(setContextOp(ctx, ciq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chaininfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ciq *ChainInfoQuery) FirstX(ctx context.Context) *ChainInfo {
	node, err := ciq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChainInfo ID from the query.
// Returns a *NotFoundError when no ChainInfo ID was found.
func (ciq *ChainInfoQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ciq.Limit(1).IDs(setContextOp(ctx, ciq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chaininfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ciq *ChainInfoQuery) FirstIDX(ctx context.Context) string {
	id, err := ciq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChainInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChainInfo entity is found.
// Returns a *NotFoundError when no ChainInfo entities are found.
func (ciq *ChainInfoQuery) Only(ctx context.Context) (*ChainInfo, error) {
	nodes, err := ciq.Limit(2).All(setContextOp(ctx, ciq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chaininfo.Label}
	default:
		return nil, &NotSingularError{chaininfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ciq *ChainInfoQuery) OnlyX(ctx context.Context) *ChainInfo {
	node, err := ciq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChainInfo ID in the query.
// Returns a *NotSingularError when more than one ChainInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (ciq *ChainInfoQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ciq.Limit(2).IDs(setContextOp(ctx, ciq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chaininfo.Label}
	default:
		err = &NotSingularError{chaininfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ciq *ChainInfoQuery) OnlyIDX(ctx context.Context) string {
	id, err := ciq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChainInfos.
func (ciq *ChainInfoQuery) All(ctx context.Context) ([]*ChainInfo, error) {
	ctx = setContextOp(ctx, ciq.ctx, "All")
	if err := ciq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChainInfo, *ChainInfoQuery]()
	return withInterceptors[[]*ChainInfo](ctx, ciq, qr, ciq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ciq *ChainInfoQuery) AllX(ctx context.Context) []*ChainInfo {
	nodes, err := ciq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChainInfo IDs.
func (ciq *ChainInfoQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ciq.ctx.Unique == nil && ciq.path != nil {
		ciq.Unique(true)
	}
	ctx = setContextOp(ctx, ciq.ctx, "IDs")
	if err = ciq.Select(chaininfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ciq *ChainInfoQuery) IDsX(ctx context.Context) []string {
	ids, err := ciq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ciq *ChainInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ciq.ctx, "Count")
	if err := ciq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ciq, querierCount[*ChainInfoQuery](), ciq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ciq *ChainInfoQuery) CountX(ctx context.Context) int {
	count, err := ciq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ciq *ChainInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ciq.ctx, "Exist")
	switch _, err := ciq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ciq *ChainInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := ciq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChainInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ciq *ChainInfoQuery) Clone() *ChainInfoQuery {
	if ciq == nil {
		return nil
	}
	return &ChainInfoQuery{
		config:     ciq.config,
		ctx:        ciq.ctx.Clone(),
		order:      append([]chaininfo.OrderOption{}, ciq.order...),
		inters:     append([]Interceptor{}, ciq.inters...),
		predicates: append([]predicate.ChainInfo{}, ciq.predicates...),
		// clone intermediate query.
		sql:  ciq.sql.Clone(),
		path: ciq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProcessedBlock uint64 `json:"processed_block,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChainInfo.Query().
//		GroupBy(chaininfo.FieldProcessedBlock).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (ciq *ChainInfoQuery) GroupBy(field string, fields ...string) *ChainInfoGroupBy {
	ciq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChainInfoGroupBy{build: ciq}
	grbuild.flds = &ciq.ctx.Fields
	grbuild.label = chaininfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProcessedBlock uint64 `json:"processed_block,omitempty"`
//	}
//
//	client.ChainInfo.Query().
//		Select(chaininfo.FieldProcessedBlock).
//		Scan(ctx, &v)
func (ciq *ChainInfoQuery) Select(fields ...string) *ChainInfoSelect {
	ciq.ctx.Fields = append(ciq.ctx.Fields, fields...)
	sbuild := &ChainInfoSelect{ChainInfoQuery: ciq}
	sbuild.label = chaininfo.Label
	sbuild.flds, sbuild.scan = &ciq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChainInfoSelect configured with the given aggregations.
func (ciq *ChainInfoQuery) Aggregate(fns ...AggregateFunc) *ChainInfoSelect {
	return ciq.Select().Aggregate(fns...)
}

func (ciq *ChainInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ciq.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ciq); err != nil {
				return err
			}
		}
	}
	for _, f := range ciq.ctx.Fields {
		if !chaininfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if ciq.path != nil {
		prev, err := ciq.path(ctx)
		if err != nil {
			return err
		}
		ciq.sql = prev
	}
	return nil
}

func (ciq *ChainInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChainInfo, error) {
	var (
		nodes = []*ChainInfo{}
		_spec = ciq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChainInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChainInfo{config: ciq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ciq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ciq *ChainInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ciq.querySpec()
	_spec.Node.Columns = ciq.ctx.Fields
	if len(ciq.ctx.Fields) > 0 {
		_spec.Unique = ciq.ctx.Unique != nil && *ciq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ciq.driver, _spec)
}

func (ciq *ChainInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chaininfo.Table, chaininfo.Columns, sqlgraph.NewFieldSpec(chaininfo.FieldID, field.TypeString))
	_spec.From = ciq.sql
	if unique := ciq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ciq.path != nil {
		_spec.Unique = true
	}
	if fields := ciq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chaininfo.FieldID)
		for i := range fields {
			if fields[i] != chaininfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ciq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ciq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ciq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ciq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ciq *ChainInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ciq.driver.Dialect())
	t1 := builder.Table(chaininfo.Table)
	columns := ciq.ctx.Fields
	if len(columns) == 0 {
		columns = chaininfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ciq.sql != nil {
		selector = ciq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ciq.ctx.Unique != nil && *ciq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ciq.predicates {
		p(selector)
	}
	for _, p := range ciq.order {
		p(selector)
	}
	if offset := ciq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ciq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChainInfoGroupBy is the group-by builder for ChainInfo entities.
type ChainInfoGroupBy struct {
	selector
	build *ChainInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cigb *ChainInfoGroupBy) Aggregate(fns ...AggregateFunc) *ChainInfoGroupBy {
	cigb.fns = append(cigb.fns, fns...)
	return cigb
}

// Scan applies the selector query and scans the result into the given value.
func (cigb *ChainInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cigb.build.ctx, "GroupBy")
	if err := cigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChainInfoQuery, *ChainInfoGroupBy](ctx, cigb.build, cigb, cigb.build.inters, v)
}

func (cigb *ChainInfoGroupBy) sqlScan(ctx context.Context, root *ChainInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cigb.fns))
	for _, fn := range cigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cigb.flds)+len(cigb.fns))
		for _, f := range *cigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChainInfoSelect is the builder for selecting fields of ChainInfo entities.
type ChainInfoSelect struct {
	*ChainInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cis *ChainInfoSelect) Aggregate(fns ...AggregateFunc) *ChainInfoSelect {
	cis.fns = append(cis.fns, fns...)
	return cis
}

// Scan applies the selector query and scans the result into the given value.
func (cis *ChainInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cis.ctx, "Select")
	if err := cis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChainInfoQuery, *ChainInfoSelect](ctx, cis.ChainInfoQuery, cis, cis.inters, v)
}

func (cis *ChainInfoSelect) sqlScan(ctx context.Context, root *ChainInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cis.fns))
	for _, fn := range cis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
