// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ronin-chain/ronin-random-beacon/pkg/db/predicate"
	"github.com/ronin-chain/ronin-random-beacon/pkg/db/randomrequest"
)

// RandomRequestDelete is the builder for deleting a RandomRequest entity.
type RandomRequestDelete struct {
	config
	hooks    []Hook
	mutation *RandomRequestMutation
}

// Where appends a list predicates to the RandomRequestDelete builder.
func (rrd *RandomRequestDelete) Where(ps ...predicate.RandomRequest) *RandomRequestDelete {
	rrd.mutation.Where(ps...)
	return rrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rrd *RandomRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rrd.sqlExec, rrd.mutation, rrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rrd *RandomRequestDelete) ExecX(ctx context.Context) int {
	n, err := rrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rrd *RandomRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(randomrequest.Table, sqlgraph.NewFieldSpec(randomrequest.FieldID, field.TypeString))
	if ps := rrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rrd.mutation.done = true
	return affected, err
}

// RandomRequestDeleteOne is the builder for deleting a single RandomRequest entity.
type RandomRequestDeleteOne struct {
	rrd *RandomRequestDelete
}

// Where appends a list predicates to the RandomRequestDelete builder.
func (rrdo *RandomRequestDeleteOne) Where(ps ...predicate.RandomRequest) *RandomRequestDeleteOne {
	rrdo.rrd.mutation.Where(ps...)
	return rrdo
}

// Exec executes the deletion query.
func (rrdo *RandomRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := rrdo.rrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{randomrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rrdo *RandomRequestDeleteOne) ExecX(ctx context.Context) {
	if err := rrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
