verbosity: 4
chain_id: 2021
coordinator_address: 0xA60c1e07fa030E4B49Eb54950ADb298Ab94dD312 # VRF Legacy
coordinator_starting_block: 25769861
rpc_endpoint: https://saigon-testnet.roninchain.com/rpc
skynet_endpoint: https://skynet-test.skymavis.one
