// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChainInfosColumns holds the columns for the "chain_infos" table.
	ChainInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "processed_block", Type: field.TypeUint64, Default: 0},
		{Name: "finalized_block", Type: field.TypeUint64, Default: 0},
	}
	// ChainInfosTable holds the schema information for the "chain_infos" table.
	ChainInfosTable = &schema.Table{
		Name:       "chain_infos",
		Columns:    ChainInfosColumns,
		PrimaryKey: []*schema.Column{ChainInfosColumns[0]},
	}
	// RandomRequestsColumns holds the columns for the "random_requests" table.
	RandomRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "block_number", Type: field.TypeUint64},
		{Name: "log_index", Type: field.TypeUint},
		{Name: "raw", Type: field.TypeString},
		{Name: "period", Type: field.TypeUint64},
		{Name: "previous_beacon", Type: field.TypeUint64},
		{Name: "task_randomrequest", Type: field.TypeInt, Nullable: true},
	}
	// RandomRequestsTable holds the schema information for the "random_requests" table.
	RandomRequestsTable = &schema.Table{
		Name:       "random_requests",
		Columns:    RandomRequestsColumns,
		PrimaryKey: []*schema.Column{RandomRequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "random_requests_tasks_randomrequest",
				Columns:    []*schema.Column{RandomRequestsColumns[6]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tx_hash", Type: field.TypeString, Nullable: true},
		{Name: "data", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "sent", "success", "failed"}},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "re_org", Type: field.TypeBool, Default: false},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "last_sent", Type: field.TypeInt, Nullable: true},
		{Name: "is_finalized", Type: field.TypeBool, Default: false},
		{Name: "sent_block", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeInt},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "task_status",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[3]},
			},
			{
				Name:    "task_is_finalized",
				Unique:  false,
				Columns: []*schema.Column{TasksColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChainInfosTable,
		RandomRequestsTable,
		TasksTable,
	}
)

func init() {
	RandomRequestsTable.ForeignKeys[0].RefTable = TasksTable
}
