name: release
on:
  release:
    types: [published]
    tags:
      - v*.*.*

env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: ronin-chain/ronin-random-beacon
  DOCKER_FILE: Dockerfile
jobs:
  push_to_docker_registry:
    name: Push Docker image to GHCR.IO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout Repo'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' #v3.1.0

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}
          tags: |
            type=semver,event=tag,suffix=-{{sha}},pattern={{raw}}
      # Enable Registry Cache
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb" #v3.3.0

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 #v5.4.0
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
