name: main release
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: ronin-chain/ronin-random-beacon
  DOCKER_FILE: Dockerfile
jobs:
  push_to_docker_registry:
    name: Push Docker image to GHCR.IO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout Repo'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' #v4.1.7

      - name: Log in to the Container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Enable Registry Cache
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4" #v3.4.0

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 #v5.4.0
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:nightly"
