// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChainInfo is the predicate function for chaininfo builders.
type ChainInfo func(*sql.Selector)

// RandomRequest is the predicate function for randomrequest builders.
type RandomRequest func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
